//! Raw FFI bindings to libisl, generated by `build.rs` from `wrapper.h`. See
//! `docs/rust-port-design.md` §5 in the workspace root — this crate is intentionally just the
//! bindgen output plus re-exports; the safe, idiomatic wrapper lives in the sibling `isl` crate.
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
#![allow(rustdoc::broken_intra_doc_links, rustdoc::bare_urls)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
