[project]
name = "alpha-rs"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = ["alphalang"]

[tool.uv]
package = false

[tool.uv.workspace]
members = ["alphalang"]

[tool.uv.sources]
alphalang = { workspace = true }

[dependency-groups]
dev = ["prek", "pytest", "nbval", "ipython", "jupyterlab", "guppylang==1.0.1 ; python_full_version >= '3.12'"]
