//! Generates a `Makefile` (issue #22, sub-issue of #21) that compiles the C source `alphac`
//! produces into an object file and, for each generated wrapper test harness
//! (`crate::wrapper::generate_wrapper`), links it against that object file into its own
//! executable.
//!
//! Unlike [`crate::wrapper::generate_wrapper`], this only ever needs file names, not an
//! `ir::System` — a Makefile has nothing to say about program semantics, only about which
//! already-written files to compile together — so it can't fail and takes no `Result`.

use std::path::{Path, PathBuf};

const CC: &str = "cc";
const CFLAGS: &str = "-std=c99";
const LDLIBS: &str = "-lm";

/// Generates the text of a `Makefile` that compiles `c_path` to an object file and, for each path
/// in `wrapper_paths`, links that wrapper's source against the resulting object file into its own
/// executable (named after the wrapper file's own stem). Every path is referenced by file name
/// only: the Makefile is meant to sit in the same directory as `c_path` and each wrapper — `alphac
/// --wrapper --makefile`'s own convention, matching issue #21's "same directory as the source
/// file" requirement — so baking in their original (possibly temporary/build-machine-specific)
/// directory would only make the Makefile less portable.
pub fn generate_makefile(c_path: &Path, wrapper_paths: &[PathBuf]) -> String {
    let c_name = file_name(c_path, "output.c");
    let obj_name = format!("{}.o", stem(c_path, "output"));

    let wrappers: Vec<(String, String)> = wrapper_paths
        .iter()
        .map(|p| (file_name(p, "wrapper.c"), stem(p, "wrapper")))
        .collect();

    let mut targets = vec![obj_name.clone()];
    targets.extend(wrappers.iter().map(|(_, exe)| exe.clone()));

    let mut out = String::new();
    out.push_str(
        "# Auto-generated by alphac (alpha-rs). Compiles the generated C source and, if\n",
    );
    out.push_str("# present, its test wrapper harness(es), produced by `alphac --makefile`.\n\n");
    out.push_str(&format!(
        "CC = {CC}\nCFLAGS = {CFLAGS}\nLDLIBS = {LDLIBS}\n\n"
    ));
    out.push_str(".PHONY: all clean\n\n");
    out.push_str(&format!("all: {}\n\n", targets.join(" ")));

    out.push_str(&format!(
        "{obj_name}: {c_name}\n\t$(CC) $(CFLAGS) -c {c_name} -o {obj_name}\n\n"
    ));

    for (wrapper_name, exe_name) in &wrappers {
        out.push_str(&format!(
            "{exe_name}: {wrapper_name} {obj_name}\n\t$(CC) $(CFLAGS) -o {exe_name} {wrapper_name} {obj_name} $(LDLIBS)\n\n"
        ));
    }

    out.push_str("clean:\n\trm -f ");
    out.push_str(&targets.join(" "));
    out.push('\n');

    out
}

fn file_name(p: &Path, default: &str) -> String {
    p.file_name()
        .and_then(|s| s.to_str())
        .unwrap_or(default)
        .to_string()
}

fn stem(p: &Path, default: &str) -> String {
    p.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or(default)
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_wrapper_only_compiles_the_object_file() {
        let mk = generate_makefile(Path::new("foo.c"), &[]);
        assert!(mk.contains("all: foo.o\n"));
        assert!(mk.contains("foo.o: foo.c"));
        assert!(mk.contains("$(CC) $(CFLAGS) -c foo.c -o foo.o"));
        assert!(!mk.contains("_wrapper:"));
    }

    #[test]
    fn single_wrapper_links_it_against_the_object_file() {
        let mk = generate_makefile(
            Path::new("dir/foo.c"),
            &[PathBuf::from("dir/foo_wrapper.c")],
        );
        assert!(mk.contains("all: foo.o foo_wrapper\n"));
        assert!(mk.contains("foo_wrapper: foo_wrapper.c foo.o"));
        assert!(mk.contains("$(CC) $(CFLAGS) -o foo_wrapper foo_wrapper.c foo.o $(LDLIBS)"));
    }

    #[test]
    fn multiple_wrappers_each_get_their_own_executable() {
        let mk = generate_makefile(
            Path::new("dir/foo.c"),
            &[
                PathBuf::from("dir/foo_A_wrapper.c"),
                PathBuf::from("dir/foo_B_wrapper.c"),
            ],
        );
        assert!(mk.contains("all: foo.o foo_A_wrapper foo_B_wrapper\n"));
        assert!(mk.contains("foo_A_wrapper: foo_A_wrapper.c foo.o"));
        assert!(mk.contains("foo_B_wrapper: foo_B_wrapper.c foo.o"));
    }

    #[test]
    fn missing_file_name_falls_back_to_a_default() {
        let mk = generate_makefile(Path::new("/"), &[]);
        assert!(mk.contains("all: output.o\n"));
    }
}
